[package]
name = "jsonld_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "jsonld_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
semver = "1.0"
thiserror = "1.0"
lazy_static = "1.4"
indexmap = { version = "2.0", features = ["serde"] }
url = "2.4"
regex = "1.10"
chrono = { version = "0.4", features = ["serde"] }
rayon = { version = "1.8", optional = true }
lru = "0.12"
uuid = { version = "1.6", features = ["v4", "serde"] }
ahash = "0.8"
memchr = { version = "2.7", optional = true }
simdutf8 = "0.1"
bumpalo = "3.14"
wide = { version = "0.7", optional = true }
# Diff algorithm dependencies
similar = "2.3"
diffy = "0.3"
hashbrown = "0.14"
bitvec = "1.0"
smallvec = "1.11"
once_cell = "1.19"

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"

# BUILD: Advanced build profiles for different use cases
[profile.release]
lto = "fat"  # Full LTO for maximum optimization
opt-level = 3
codegen-units = 1
panic = "abort"  # Smaller binaries, faster performance
strip = true     # Strip debug symbols
debug = false

[profile.dev]
opt-level = 1    # Some optimization in dev for faster local testing
debug = true
overflow-checks = true

# BUILD: High-performance release profile for production
[profile.production]
inherits = "release"
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
debug = false
rpath = false

# BUILD: Fast build profile for CI/development iterations
[profile.fast-build]
inherits = "dev"
opt-level = 1
debug = false
strip = true
incremental = true

# BUILD: Benchmarking profile
[profile.bench]
inherits = "release"
debug = true      # Keep symbols for profiling
strip = false

[features]
default = ["parallel", "simd"]
parallel = ["rayon"]
simd = ["wide", "memchr"]
fast-build = []
production = []